
model_path: model_zoos.final_alpha_model.LightMMOE
model_name: spring_alpha

wide_encoder:
  dropout: 0.1
  feat_dim: 103
  proj_dim: 200
  context_dim: 64
  output_dim: 32

seq_encoder:
  dropout: 0.1
  num_input: 100
  output_size: 32
  num_channels: [64, 64, 32]
  kernel_size: 4


dropout: 0.1
stock_dim: 32
week_class: 7
week_dim: 32
session_class: 4
session_dim: 32
minute_class: 48
minute_dim: 32

expert_size: 64
expert_number: 8
task_number: 12
device: cpu
stock_class: 90
batch_size: 1024